version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        # wait for https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/issues/122
      - dependency-name: "tonic-tracing-opentelemetry"
        # wait for tonic : https://github.com/hyperium/tonic/issues/1579
      - dependency-name: "http"
      - dependency-name: "hyper"
      - dependency-name: "axum"
      - dependency-name: "http-body"
      - dependency-name: "tower-http"
    groups:
      tonic:
        patterns:
          - "tonic"
          - "tonic-health"
          - "tonic-web"
          - "tonic-reflection"
          - "tonic-build"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/modules/web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    ignore:
      # - dependency-name: "*"
      #   update-types: ["version-update:semver-patch"]
      # don't try to update internal packages
      - dependency-name: "@md/*"
      - dependency-name: "@meteroid/*"
