version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    groups:
      tonic:
        patterns:
          - "tonic"
          - "tonic-health"
          - "tonic-web"
          - "tonic-reflection"
      prost:
        patterns:
          - "prost"
          - "prost-build"
          - "prost-types"
      opentelemetry:
        patterns:
          - "opentelemetry"
          - "opentelemetry_sdk"
          - "opentelemetry-otlp"
          - "opentelemetry-appender-tracing"
      build-info:
        patterns:
          - "build-info"
          - "build-info-build"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/modules/web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    ignore:
      # - dependency-name: "*"
      #   update-types: ["version-update:semver-patch"]
      # don't try to update internal packages
      - dependency-name: "@md/*"
      - dependency-name: "@meteroid/*"
