name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'chore'
    title:
      - '^chore(?:\(([^\)]*)\))?:(.*)$'
      - '^test(?:\(([^\)]*)\))?:(.*)$'
  - label: 'bug'
    title:
      - '^bug(?:\(([^\)]*)\))?:(.*)$'
      - '^bugfix(?:\(([^\)]*)\))?:(.*)$'
      - '^fix(?:\(([^\)]*)\))?:(.*)$'
      - '^hotfix(?:\(([^\)]*)\))?:(.*)$'
  - label: 'feature'
    title:
      - '^feat(?:\(([^\)]*)\))?:(.*)$'
      - '^feature(?:\(([^\)]*)\))?:(.*)$'
