# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli


[migrations_directory]
dir = "modules/meteroid/migrations/diesel"

[print_schema]
file = "modules/meteroid/crates/diesel-models/src/schema.rs"
#import_types = ["diesel::sql_types::*", "crate::domains::models::enums::*"]
custom_type_derives = ["diesel::query_builder::QueryId"]
#generate_missing_sql_type_definitions = false
