# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: OpenSearch
    type: grafana-opensearch-datasource
    url: http://opensearch:9200/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      database: otel
      flavor: opensearch
      logLevelField: severity
      logMessageField: body
      pplEnabled: true
      timeField: observedTimestamp
      version: 2.18.0
