[package]
name = "golden"
version = "1.0.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
paste.workspace = true
