apiVersion: v1
kind: Service
metadata:
  name: {{ include "meteroid.webFullname" . }}
  labels:
    {{- include "meteroid.webLabels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    {{- toYaml .Values.web.service.ports | nindent 4 }}
  selector:
    {{- include "meteroid.webSelectorLabels" . | nindent 4 }}
