### List customers/compamies https://pennylane.readme.io/v2.0/reference/getcustomers
GET https://app.pennylane.com/api/external/v2/customers HTTP/1.1
Accept: application/json
Authorization: Bearer {{api_token}}

### Create a company customer https://pennylane.readme.io/v2.0/reference/postcompanycustomer
POST https://app.pennylane.com/api/external/v2/company_customers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{api_token}}

{
  "name": "first_test_company",
  "billing_address": {
    "address": "Gates 50",
    "postal_code": "50-001",
    "city": "Wroclaw",
    "country_alpha2": "PL"
  },
  "external_reference": "cus_123456789"
}

### Update a company customer https://pennylane.readme.io/v2.0/reference/putcompanycustomer
PUT https://app.pennylane.com/api/external/v2/company_customers/157896015
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{api_token}}

{
  "name": "first_test_company",
  "billing_address": {
    "address": "Gates 50",
    "postal_code": "50-001",
    "city": "Wroclaw",
    "country_alpha2": "PL"
  },
  "external_reference": "cus_123456789"
}

### customer invoices changelog https://pennylane.readme.io/v2.0/docs/tracking-data-changes-with-pennylane-api#available-changelog-endpoints
GET https://app.pennylane.com/api/external/v2/changelogs/customer_invoices HTTP/1.1
Accept: application/json
Authorization: Bearer {{api_token}}

### Upload file https://pennylane.readme.io/v2.0/reference/postfileattachments
POST https://app.pennylane.com/api/external/v2/file_attachments HTTP/1.1
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{api_token}}

--MyBoundary
Content-Disposition: form-data; name="file"; filename="custom_name.pdf"
Content-Type: application/pdf

< ./inv_sample.pdf
--MyBoundary--


### Import customer invoice https://pennylane.readme.io/v2.0/reference/importcustomerinvoices
POST https://app.pennylane.com/api/external/v2/customer_invoices/import HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{api_token}}

{
  "file_attachment_id": 1141709,
  "external_reference": "inv_123456789",
  "invoice_number": "PL00001",
  "date": "2025-05-01",
  "deadline": "2025-05-01",
  "customer_id": 157896015,
  "currency": "EUR",
  "currency_amount_before_tax": "200.1",
  "currency_amount": "220.1",
  "amount": "220.1",
  "currency_tax": "20",
  "invoice_lines": [
    {
      "currency_amount": "220.1",
      "amount": "220.1",
      "currency_tax": "20",
      "label": "Test line",
      "quantity": 1.5,
      "raw_currency_unit_price": "20.01",
      "unit": "units",
      "vat_rate": "PL_230"
    }
  ]
}

### Mark customer invoice as paid https://pennylane.readme.io/v2.0/reference/markaspaidcustomerinvoice
PUT https://app.pennylane.com/api/external/v2/customer_invoices/1974109344/mark_as_paid
Authorization: Bearer {{api_token}}

### List customer invoices https://pennylane.readme.io/v2.0/reference/getcustomerinvoices
GET https://app.pennylane.com/api/external/v2/customer_invoices HTTP/1.1
Accept: application/json
Authorization: Bearer {{api_token}}

### Get customer by external_reference https://pennylane.readme.io/v2.0/reference/getcustomers
GET https://app.pennylane.com/api/external/v2/customers?
  filter=[{"field": "external_reference", "operator": "eq", "value": "cus_VTNnzVXRsjJuusdcEPVtl"}] HTTP/1.1
Accept: application/json
Authorization: Bearer {{api_token}}

### Get invoice by external_reference https://pennylane.readme.io/v2.0/reference/getcustomers
GET https://app.pennylane.com/api/external/v2/customer_invoices?
  filter=[{"field": "external_reference", "operator": "eq", "value": "inv_123456789"}] HTTP/1.1
Accept: application/json
Authorization: Bearer {{api_token}}

