[package]
name = "pennylane-client"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
secrecy = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true, features = ["default", "multipart"] }
reqwest-retry = { workspace = true, features = ["default"] }
reqwest-middleware = { workspace = true, features = ["json", "multipart"] }
async-trait = { workspace = true }
nonzero_ext = { workspace = true }
meteroid-middleware = { workspace = true, features = ["client"] }
bytes = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
