[package]
name = "metering"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rand.workspace = true
async-trait.workspace = true
backon.workspace = true
cached = { workspace = true, features = ["async", "tokio", "redis_store", "redis_tokio"] }
chrono.workspace = true
chrono-tz.workspace = true
clickhouse-rs.workspace = true
common-config.workspace = true
common-logging.workspace = true
dotenvy.workspace = true
envconfig.workspace = true
error-stack.workspace = true
futures.workspace = true
kafka.workspace = true
log.workspace = true
metering-grpc = { workspace = true, features = ["server"] }
meteroid-grpc = { workspace = true, features = ["client"] }
common-grpc = { workspace = true, features = ["server", "client"] }
rdkafka = { workspace = true, features = ["ssl", "sasl"] }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
tower = { workspace = true }
tower-layer = { workspace = true }
tower-service = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tonic-tracing-opentelemetry.workspace = true
once_cell = { workspace = true }
opentelemetry = { workspace = true }
uuid = { version = "1.6.1", features = ["v4"] }
common-utils = { workspace = true, features = ["error-stack-conv"] }
prost-types.workspace = true
quick_cache.workspace = true

[[bin]]
name = "metering-api"
path = "src/bin/server.rs"
