apiVersion: v2
name: meteroid
description: Helm chart for Meteroid
version: 0.1.0
type: application
dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: "31.3.1"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
