{
 "title": "gRPC summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "grpc_service", "label": "gRPC Service", "query": { "query": "label_values(grpc_service)" } }
  ]
 },
 "panels": [
  {
   "title": "Client throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_service, grpc_method) (rate(grpc_call_counter_total{grpc_kind=\"client\", grpc_service=~\"$grpc_service\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_service}}#{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Client throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_status, grpc_service) (rate(grpc_call_counter_total{grpc_kind=\"client\", grpc_service=~\"$grpc_service\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_service}}:{{grpc_status}}"
    }
   ]
  },
  {
   "title": "Client latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, grpc_service, grpc_method) (rate(grpc_call_latency_bucket{grpc_kind=\"client\", grpc_service=~\"$grpc_service\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_service}}#{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Server throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_method, grpc_service) (rate(grpc_call_counter_total{grpc_kind=\"server\", grpc_service=~\"$grpc_service\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_service}}#{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Server throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_status, grpc_service) (rate(grpc_call_counter_total{grpc_kind=\"server\", grpc_service=~\"$grpc_service\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_service}}:{{grpc_status}}"
    }
   ]
  },
  {
   "title": "Server latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, grpc_service, grpc_method) (rate(grpc_call_latency_bucket{grpc_kind=\"server\", grpc_service=~\"$grpc_service\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_service}}#{{grpc_method}}"
    }
   ]
  }
 ]
}