[package]
name = "cornucopia-build"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cornucopia.workspace = true
miette = { workspace = true, features = ["fancy", "derive"] }
postgres.workspace = true
thiserror.workspace = true
