x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

volumes:
  pg_data:

networks:
  meteroid_net:

name: meteroid-lite

services:

  ### Meteroid Dependencies
  meteroid-db:
    image: ghcr.io/meteroid-oss/meteroid-postgres:17.4
    container_name: meteroid-db
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER:-meteroid}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME:-meteroid}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    networks:
      - meteroid_net

