name: meteroid-lite

volumes:
  pg_data:
  clickhouse_data:
  minio_data:
  redpanda_data:

networks:
  meteroid_net:

services:

  # The database is all you need to start Meteroid in degraded mode for development.
  meteroid-db:
    extends:
      file: docker-compose.yml
      service: meteroid-db

  # All other services are disabled by default
  # and can be enabled using profiles ex: --profile full

  svix-server:
    extends:
      file: docker-compose.yml
      service: svix-server
    profiles:
      - webhook
      - full

  pgbouncer:
    extends:
      file: docker-compose.yml
      service: pgbouncer
    profiles:
      - webhook
      - full

  minio:
    extends:
      file: docker-compose.yml
      service: minio
    profiles:
      - storage
      - full

  createbuckets:
    extends:
      file: docker-compose.yml
      service: createbuckets
    profiles:
      - storage
      - full

  clickhouse:
    extends:
      file: docker-compose.yml
      service: clickhouse
    profiles:
      - metering
      - full

  redpanda:
    extends:
      file: docker-compose.yml
      service: redpanda
    profiles:
      - metering
      - full

  redpanda-console:
    extends:
      file: docker-compose.yml
      service: redpanda-console
    profiles:
      - metering
      - full

  redpanda-topic-create:
    extends:
      file: docker-compose.yml
      service: redpanda-topic-create
    profiles:
      - metering
      - full



