export type Country = {
  code: string
  flag: string
  mobileCode: string
  name: string
  timezone: string
  utc: string
}

export const countries: Record<string, Country> = {
  AF: {
    name: `Afghanistan`,
    code: `AF`,
    timezone: `Afghanistan Standard Time`,
    utc: `UTC+04:30`,
    mobileCode: `+93`,
    flag: `🇦🇫`,
  },
  AX: {
    name: `Åland Islands`,
    code: `AX`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+358-18`,
    flag: `🇦🇽`,
  },
  AL: {
    name: `Albania`,
    code: `AL`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+355`,
    flag: `🇦🇱`,
  },
  DZ: {
    name: `Algeria`,
    code: `DZ`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+213`,
    flag: `🇩🇿`,
  },
  AS: {
    name: `American Samoa`,
    code: `AS`,
    timezone: `UTC-11`,
    utc: `UTC-11:00`,
    mobileCode: `+1-684`,
    flag: `🇦🇸`,
  },
  AD: {
    name: `Andorra`,
    code: `AD`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+376`,
    flag: `🇦🇩`,
  },
  AO: {
    name: `Angola`,
    code: `AO`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+244`,
    flag: `🇦🇴`,
  },
  AI: {
    name: `Anguilla`,
    code: `AI`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-264`,
    flag: `🇦🇮`,
  },
  AQ: {
    name: `Antarctica`,
    code: `AQ`,
    timezone: `Pacific SA Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+`,
    flag: `🇦🇶`,
  },
  AG: {
    name: `Antigua and Barbuda`,
    code: `AG`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-268`,
    flag: `🇦🇬`,
  },
  AR: {
    name: `Argentina`,
    code: `AR`,
    timezone: `Argentina Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+54`,
    flag: `🇦🇷`,
  },
  AM: {
    name: `Armenia`,
    code: `AM`,
    timezone: `Caucasus Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+374`,
    flag: `🇦🇲`,
  },
  AW: {
    name: `Aruba`,
    code: `AW`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+297`,
    flag: `🇦🇼`,
  },
  AU: {
    name: `Australia`,
    code: `AU`,
    timezone: `AUS Eastern Standard Time`,
    utc: `UTC+10:00`,
    mobileCode: `+61`,
    flag: `🇦🇺`,
  },
  AT: {
    name: `Austria`,
    code: `AT`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+43`,
    flag: `🇦🇹`,
  },
  AZ: {
    name: `Azerbaijan`,
    code: `AZ`,
    timezone: `Azerbaijan Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+994`,
    flag: `🇦🇿`,
  },
  BS: {
    name: `Bahamas, The`,
    code: `BS`,
    timezone: `Eastern Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+1-242`,
    flag: `🇧🇸`,
  },
  BH: {
    name: `Bahrain`,
    code: `BH`,
    timezone: `Arab Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+973`,
    flag: `🇧🇭`,
  },
  BD: {
    name: `Bangladesh`,
    code: `BD`,
    timezone: `Bangladesh Standard Time`,
    utc: `UTC+06:00`,
    mobileCode: `+880`,
    flag: `🇧🇩`,
  },
  BB: {
    name: `Barbados`,
    code: `BB`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-246`,
    flag: `🇧🇧`,
  },
  BY: {
    name: `Belarus`,
    code: `BY`,
    timezone: `Belarus Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+375`,
    flag: `🇧🇾`,
  },
  BE: {
    name: `Belgium`,
    code: `BE`,
    timezone: `Romance Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+32`,
    flag: `🇧🇪`,
  },
  BZ: {
    name: `Belize`,
    code: `BZ`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+501`,
    flag: `🇧🇿`,
  },
  BJ: {
    name: `Benin`,
    code: `BJ`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+229`,
    flag: `🇧🇯`,
  },
  BM: {
    name: `Bermuda`,
    code: `BM`,
    timezone: `Atlantic Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-441`,
    flag: `🇧🇲`,
  },
  BT: {
    name: `Bhutan`,
    code: `BT`,
    timezone: `Bangladesh Standard Time`,
    utc: `UTC+06:00`,
    mobileCode: `+975`,
    flag: `🇧🇹`,
  },
  VE: {
    name: `Bolivarian Republic of Venezuela`,
    code: `VE`,
    timezone: `Venezuela Standard Time`,
    utc: `UTC-04:30`,
    mobileCode: `+58`,
    flag: `🇻🇪`,
  },
  BO: {
    name: `Bolivia`,
    code: `BO`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+591`,
    flag: `🇧🇴`,
  },
  BQ: {
    name: `Caribbean Netherlands`,
    code: `BQ`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+599`,
    flag: `🇧🇶`,
  },
  BA: {
    name: `Bosnia and Herzegovina`,
    code: `BA`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+387`,
    flag: `🇧🇦`,
  },
  BW: {
    name: `Botswana`,
    code: `BW`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+267`,
    flag: `🇧🇼`,
  },
  BV: {
    name: `Bouvet Island`,
    code: `BV`,
    timezone: `UTC`,
    utc: `UTC`,
    mobileCode: `+`,
    flag: `🇧🇻`,
  },
  BR: {
    name: `Brazil`,
    code: `BR`,
    timezone: `E. South America Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+55`,
    flag: `🇧🇷`,
  },
  IO: {
    name: `British Indian Ocean Territory`,
    code: `IO`,
    timezone: `Central Asia Standard Time`,
    utc: `UTC+06:00`,
    mobileCode: `+246`,
    flag: `🇮🇴`,
  },
  BN: {
    name: `Brunei`,
    code: `BN`,
    timezone: `Singapore Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+673`,
    flag: `🇧🇳`,
  },
  BG: {
    name: `Bulgaria`,
    code: `BG`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+359`,
    flag: `🇧🇬`,
  },
  BF: {
    name: `Burkina Faso`,
    code: `BF`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+226`,
    flag: `🇧🇫`,
  },
  BI: {
    name: `Burundi`,
    code: `BI`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+257`,
    flag: `🇧🇮`,
  },
  CV: {
    name: `Cabo Verde`,
    code: `CV`,
    timezone: `Cape Verde Standard Time`,
    utc: `UTC-01:00`,
    mobileCode: `+238`,
    flag: `🇨🇻`,
  },
  KH: {
    name: `Cambodia`,
    code: `KH`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+855`,
    flag: `🇰🇭`,
  },
  CM: {
    name: `Cameroon`,
    code: `CM`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+237`,
    flag: `🇨🇲`,
  },
  CA: {
    name: `Canada`,
    code: `CA`,
    timezone: `Eastern Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+1`,
    flag: `🇨🇦`,
  },
  KY: {
    name: `Cayman Islands`,
    code: `KY`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+1-345`,
    flag: `🇰🇾`,
  },
  CF: {
    name: `Central African Republic`,
    code: `CF`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+236`,
    flag: `🇨🇫`,
  },
  TD: {
    name: `Chad`,
    code: `TD`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+235`,
    flag: `🇹🇩`,
  },
  CL: {
    name: `Chile`,
    code: `CL`,
    timezone: `Pacific SA Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+56`,
    flag: `🇨🇱`,
  },
  CN: {
    name: `China`,
    code: `CN`,
    timezone: `China Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+86`,
    flag: `🇨🇳`,
  },
  CX: {
    name: `Christmas Island`,
    code: `CX`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+61`,
    flag: `🇨🇽`,
  },
  CC: {
    name: `Cocos (Keeling) Islands`,
    code: `CC`,
    timezone: `Myanmar Standard Time`,
    utc: `UTC+06:30`,
    mobileCode: `+61`,
    flag: `🇨🇨`,
  },
  CO: {
    name: `Colombia`,
    code: `CO`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+57`,
    flag: `🇨🇴`,
  },
  KM: {
    name: `Comoros`,
    code: `KM`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+269`,
    flag: `🇰🇲`,
  },
  CG: {
    name: `Congo`,
    code: `CG`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+242`,
    flag: `🇨🇬`,
  },
  CD: {
    name: `Congo (DRC)`,
    code: `CD`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+243`,
    flag: `🇨🇩`,
  },
  CK: {
    name: `Cook Islands`,
    code: `CK`,
    timezone: `Hawaiian Standard Time`,
    utc: `UTC-10:00`,
    mobileCode: `+682`,
    flag: `🇨🇰`,
  },
  CR: {
    name: `Costa Rica`,
    code: `CR`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+506`,
    flag: `🇨🇷`,
  },
  CI: {
    name: `Côte d'Ivoire`,
    code: `CI`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+225`,
    flag: `🇨🇮`,
  },
  HR: {
    name: `Croatia`,
    code: `HR`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+385`,
    flag: `🇭🇷`,
  },
  CU: {
    name: `Cuba`,
    code: `CU`,
    timezone: `Eastern Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+53`,
    flag: `🇨🇺`,
  },
  CW: {
    name: `Curaçao`,
    code: `CW`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+599`,
    flag: `🇨🇼`,
  },
  CY: {
    name: `Cyprus`,
    code: `CY`,
    timezone: `E. Europe Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+357`,
    flag: `🇨🇾`,
  },
  CZ: {
    name: `Czech Republic`,
    code: `CZ`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+420`,
    flag: `🇨🇿`,
  },
  TL: {
    name: `Democratic Republic of Timor-Leste`,
    code: `TL`,
    timezone: `Tokyo Standard Time`,
    utc: `UTC+09:00`,
    mobileCode: `+670`,
    flag: `🇹🇱`,
  },
  DK: {
    name: `Denmark`,
    code: `DK`,
    timezone: `Romance Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+45`,
    flag: `🇩🇰`,
  },
  DJ: {
    name: `Djibouti`,
    code: `DJ`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+253`,
    flag: `🇩🇯`,
  },
  DM: {
    name: `Dominica`,
    code: `DM`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-767`,
    flag: `🇩🇲`,
  },
  DO: {
    name: `Dominican Republic`,
    code: `DO`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-809 and 1-829`,
    flag: `🇩🇴`,
  },
  EC: {
    name: `Ecuador`,
    code: `EC`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+593`,
    flag: `🇪🇨`,
  },
  EG: {
    name: `Egypt`,
    code: `EG`,
    timezone: `Egypt Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+20`,
    flag: `🇪🇬`,
  },
  SV: {
    name: `El Salvador`,
    code: `SV`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+503`,
    flag: `🇸🇻`,
  },
  GQ: {
    name: `Equatorial Guinea`,
    code: `GQ`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+240`,
    flag: `🇬🇶`,
  },
  ER: {
    name: `Eritrea`,
    code: `ER`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+291`,
    flag: `🇪🇷`,
  },
  EE: {
    name: `Estonia`,
    code: `EE`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+372`,
    flag: `🇪🇪`,
  },
  ET: {
    name: `Ethiopia`,
    code: `ET`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+251`,
    flag: `🇪🇹`,
  },
  FK: {
    name: `Falkland Islands (Islas Malvinas)`,
    code: `FK`,
    timezone: `SA Eastern Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+500`,
    flag: `🇫🇰`,
  },
  FO: {
    name: `Faroe Islands`,
    code: `FO`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+298`,
    flag: `🇫🇴`,
  },
  FJ: {
    name: `Fiji Islands`,
    code: `FJ`,
    timezone: `Fiji Standard Time`,
    utc: `UTC+12:00`,
    mobileCode: `+679`,
    flag: `🇫🇯`,
  },
  FI: {
    name: `Finland`,
    code: `FI`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+358`,
    flag: `🇫🇮`,
  },
  FR: {
    name: `France`,
    code: `FR`,
    timezone: `Romance Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+33`,
    flag: `🇫🇷`,
  },
  GF: {
    name: `French Guiana`,
    code: `GF`,
    timezone: `SA Eastern Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+594`,
    flag: `🇬🇫`,
  },
  PF: {
    name: `French Polynesia`,
    code: `PF`,
    timezone: `Hawaiian Standard Time`,
    utc: `UTC-10:00`,
    mobileCode: `+689`,
    flag: `🇵🇫`,
  },
  TF: {
    name: `French Southern and Antarctic Lands`,
    code: `TF`,
    timezone: `West Asia Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+`,
    flag: `🇹🇫`,
  },
  GA: {
    name: `Gabon`,
    code: `GA`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+241`,
    flag: `🇬🇦`,
  },
  GM: {
    name: `Gambia, The`,
    code: `GM`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+220`,
    flag: `🇬🇲`,
  },
  GE: {
    name: `Georgia`,
    code: `GE`,
    timezone: `Georgian Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+995`,
    flag: `🇬🇪`,
  },
  DE: {
    name: `Germany`,
    code: `DE`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+49`,
    flag: `🇩🇪`,
  },
  GH: {
    name: `Ghana`,
    code: `GH`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+233`,
    flag: `🇬🇭`,
  },
  GI: {
    name: `Gibraltar`,
    code: `GI`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+350`,
    flag: `🇬🇮`,
  },
  GR: {
    name: `Greece`,
    code: `GR`,
    timezone: `GTB Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+30`,
    flag: `🇬🇷`,
  },
  GL: {
    name: `Greenland`,
    code: `GL`,
    timezone: `Greenland Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+299`,
    flag: `🇬🇱`,
  },
  GD: {
    name: `Grenada`,
    code: `GD`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-473`,
    flag: `🇬🇩`,
  },
  GP: {
    name: `Guadeloupe`,
    code: `GP`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+590`,
    flag: `🇬🇵`,
  },
  GU: {
    name: `Guam`,
    code: `GU`,
    timezone: `West Pacific Standard Time`,
    utc: `UTC+10:00`,
    mobileCode: `+1-671`,
    flag: `🇬🇺`,
  },
  GT: {
    name: `Guatemala`,
    code: `GT`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+502`,
    flag: `🇬🇹`,
  },
  GG: {
    name: `Guernsey`,
    code: `GG`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+44-1481`,
    flag: `🇬🇬`,
  },
  GN: {
    name: `Guinea`,
    code: `GN`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+224`,
    flag: `🇬🇳`,
  },
  GW: {
    name: `Guinea-Bissau`,
    code: `GW`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+245`,
    flag: `🇬🇼`,
  },
  GY: {
    name: `Guyana`,
    code: `GY`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+592`,
    flag: `🇬🇾`,
  },
  HT: {
    name: `Haiti`,
    code: `HT`,
    timezone: `Eastern Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+509`,
    flag: `🇭🇹`,
  },
  HM: {
    name: `Heard Island and McDonald Islands`,
    code: `HM`,
    timezone: `Mauritius Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+ `,
    flag: `🇭🇲`,
  },
  HN: {
    name: `Honduras`,
    code: `HN`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+504`,
    flag: `🇭🇳`,
  },
  HK: {
    name: `Hong Kong SAR`,
    code: `HK`,
    timezone: `China Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+852`,
    flag: `🇭🇰`,
  },
  HU: {
    name: `Hungary`,
    code: `HU`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+36`,
    flag: `🇭🇺`,
  },
  IS: {
    name: `Iceland`,
    code: `IS`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+354`,
    flag: `🇮🇸`,
  },
  IN: {
    name: `India`,
    code: `IN`,
    timezone: `India Standard Time`,
    utc: `UTC+05:30`,
    mobileCode: `+91`,
    flag: `🇮🇳`,
  },
  ID: {
    name: `Indonesia`,
    code: `ID`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+62`,
    flag: `🇮🇩`,
  },
  IR: {
    name: `Iran`,
    code: `IR`,
    timezone: `Iran Standard Time`,
    utc: `UTC+03:30`,
    mobileCode: `+98`,
    flag: `🇮🇷`,
  },
  IQ: {
    name: `Iraq`,
    code: `IQ`,
    timezone: `Arabic Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+964`,
    flag: `🇮🇶`,
  },
  IE: {
    name: `Ireland`,
    code: `IE`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+353`,
    flag: `🇮🇪`,
  },
  IL: {
    name: `Israel`,
    code: `IL`,
    timezone: `Israel Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+972`,
    flag: `🇮🇱`,
  },
  IT: {
    name: `Italy`,
    code: `IT`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+39`,
    flag: `🇮🇹`,
  },
  JM: {
    name: `Jamaica`,
    code: `JM`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+1-876`,
    flag: `🇯🇲`,
  },
  SJ: {
    name: `Svalbard`,
    code: `SJ`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+47`,
    flag: `🇸🇯`,
  },
  JP: {
    name: `Japan`,
    code: `JP`,
    timezone: `Tokyo Standard Time`,
    utc: `UTC+09:00`,
    mobileCode: `+81`,
    flag: `🇯🇵`,
  },
  JE: {
    name: `Jersey`,
    code: `JE`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+44-1534`,
    flag: `🇯🇪`,
  },
  JO: {
    name: `Jordan`,
    code: `JO`,
    timezone: `Jordan Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+962`,
    flag: `🇯🇴`,
  },
  KZ: {
    name: `Kazakhstan`,
    code: `KZ`,
    timezone: `Central Asia Standard Time`,
    utc: `UTC+06:00`,
    mobileCode: `+7`,
    flag: `🇰🇿`,
  },
  KE: {
    name: `Kenya`,
    code: `KE`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+254`,
    flag: `🇰🇪`,
  },
  KI: {
    name: `Kiribati`,
    code: `KI`,
    timezone: `UTC+12`,
    utc: `UTC+12:00`,
    mobileCode: `+686`,
    flag: `🇰🇮`,
  },
  KR: {
    name: `Korea`,
    code: `KR`,
    timezone: `Korea Standard Time`,
    utc: `UTC+09:00`,
    mobileCode: `+82`,
    flag: `🇰🇷`,
  },
  XK: {
    name: `Kosovo`,
    code: `XK`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+`,
    flag: `🇽🇰`,
  },
  KW: {
    name: `Kuwait`,
    code: `KW`,
    timezone: `Arab Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+965`,
    flag: `🇰🇼`,
  },
  KG: {
    name: `Kyrgyzstan`,
    code: `KG`,
    timezone: `Central Asia Standard Time`,
    utc: `UTC+06:00`,
    mobileCode: `+996`,
    flag: `🇰🇬`,
  },
  LA: {
    name: `Laos`,
    code: `LA`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+856`,
    flag: `🇱🇦`,
  },
  LV: {
    name: `Latvia`,
    code: `LV`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+371`,
    flag: `🇱🇻`,
  },
  LB: {
    name: `Lebanon`,
    code: `LB`,
    timezone: `Middle East Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+961`,
    flag: `🇱🇧`,
  },
  LS: {
    name: `Lesotho`,
    code: `LS`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+266`,
    flag: `🇱🇸`,
  },
  LR: {
    name: `Liberia`,
    code: `LR`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+231`,
    flag: `🇱🇷`,
  },
  LY: {
    name: `Libya`,
    code: `LY`,
    timezone: `E. Europe Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+218`,
    flag: `🇱🇾`,
  },
  LI: {
    name: `Liechtenstein`,
    code: `LI`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+423`,
    flag: `🇱🇮`,
  },
  LT: {
    name: `Lithuania`,
    code: `LT`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+370`,
    flag: `🇱🇹`,
  },
  LU: {
    name: `Luxembourg`,
    code: `LU`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+352`,
    flag: `🇱🇺`,
  },
  MO: {
    name: `Macao SAR`,
    code: `MO`,
    timezone: `China Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+853`,
    flag: `🇲🇴`,
  },
  MK: {
    name: `Macedonia, Former Yugoslav Republic of`,
    code: `MK`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+389`,
    flag: `🇲🇰`,
  },
  MG: {
    name: `Madagascar`,
    code: `MG`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+261`,
    flag: `🇲🇬`,
  },
  MW: {
    name: `Malawi`,
    code: `MW`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+265`,
    flag: `🇲🇼`,
  },
  MY: {
    name: `Malaysia`,
    code: `MY`,
    timezone: `Singapore Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+60`,
    flag: `🇲🇾`,
  },
  MV: {
    name: `Maldives`,
    code: `MV`,
    timezone: `West Asia Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+960`,
    flag: `🇲🇻`,
  },
  ML: {
    name: `Mali`,
    code: `ML`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+223`,
    flag: `🇲🇱`,
  },
  MT: {
    name: `Malta`,
    code: `MT`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+356`,
    flag: `🇲🇹`,
  },
  IM: {
    name: `Man, Isle of`,
    code: `IM`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+44-1624`,
    flag: `🇮🇲`,
  },
  MH: {
    name: `Marshall Islands`,
    code: `MH`,
    timezone: `UTC+12`,
    utc: `UTC+12:00`,
    mobileCode: `+692`,
    flag: `🇲🇭`,
  },
  MQ: {
    name: `Martinique`,
    code: `MQ`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+596`,
    flag: `🇲🇶`,
  },
  MR: {
    name: `Mauritania`,
    code: `MR`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+222`,
    flag: `🇲🇷`,
  },
  MU: {
    name: `Mauritius`,
    code: `MU`,
    timezone: `Mauritius Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+230`,
    flag: `🇲🇺`,
  },
  YT: {
    name: `Mayotte`,
    code: `YT`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+262`,
    flag: `🇾🇹`,
  },
  MX: {
    name: `Mexico`,
    code: `MX`,
    timezone: `Central Standard Time (Mexico)`,
    utc: `UTC-06:00`,
    mobileCode: `+52`,
    flag: `🇲🇽`,
  },
  FM: {
    name: `Micronesia`,
    code: `FM`,
    timezone: `West Pacific Standard Time`,
    utc: `UTC+10:00`,
    mobileCode: `+691`,
    flag: `🇫🇲`,
  },
  MD: {
    name: `Moldova`,
    code: `MD`,
    timezone: `GTB Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+373`,
    flag: `🇲🇩`,
  },
  MC: {
    name: `Monaco`,
    code: `MC`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+377`,
    flag: `🇲🇨`,
  },
  MN: {
    name: `Mongolia`,
    code: `MN`,
    timezone: `Ulaanbaatar Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+976`,
    flag: `🇲🇳`,
  },
  ME: {
    name: `Montenegro`,
    code: `ME`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+382`,
    flag: `🇲🇪`,
  },
  MS: {
    name: `Montserrat`,
    code: `MS`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-664`,
    flag: `🇲🇸`,
  },
  MA: {
    name: `Morocco`,
    code: `MA`,
    timezone: `Morocco Standard Time`,
    utc: `UTC`,
    mobileCode: `+212`,
    flag: `🇲🇦`,
  },
  MZ: {
    name: `Mozambique`,
    code: `MZ`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+258`,
    flag: `🇲🇿`,
  },
  MM: {
    name: `Myanmar`,
    code: `MM`,
    timezone: `Myanmar Standard Time`,
    utc: `UTC+06:30`,
    mobileCode: `+95`,
    flag: `🇲🇲`,
  },
  NA: {
    name: `Namibia`,
    code: `NA`,
    timezone: `Namibia Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+264`,
    flag: `🇳🇦`,
  },
  NR: {
    name: `Nauru`,
    code: `NR`,
    timezone: `UTC+12`,
    utc: `UTC+12:00`,
    mobileCode: `+674`,
    flag: `🇳🇷`,
  },
  NP: {
    name: `Nepal`,
    code: `NP`,
    timezone: `Nepal Standard Time`,
    utc: `UTC+05:45`,
    mobileCode: `+977`,
    flag: `🇳🇵`,
  },
  NL: {
    name: `Netherlands`,
    code: `NL`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+31`,
    flag: `🇳🇱`,
  },
  NC: {
    name: `New Caledonia`,
    code: `NC`,
    timezone: `Central Pacific Standard Time`,
    utc: `UTC+11:00`,
    mobileCode: `+687`,
    flag: `🇳🇨`,
  },
  NZ: {
    name: `New Zealand`,
    code: `NZ`,
    timezone: `New Zealand Standard Time`,
    utc: `UTC+12:00`,
    mobileCode: `+64`,
    flag: `🇳🇿`,
  },
  NI: {
    name: `Nicaragua`,
    code: `NI`,
    timezone: `Central America Standard Time`,
    utc: `UTC-06:00`,
    mobileCode: `+505`,
    flag: `🇳🇮`,
  },
  NE: {
    name: `Niger`,
    code: `NE`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+227`,
    flag: `🇳🇪`,
  },
  NG: {
    name: `Nigeria`,
    code: `NG`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+234`,
    flag: `🇳🇬`,
  },
  NU: {
    name: `Niue`,
    code: `NU`,
    timezone: `UTC-11`,
    utc: `UTC-11:00`,
    mobileCode: `+683`,
    flag: `🇳🇺`,
  },
  NF: {
    name: `Norfolk Island`,
    code: `NF`,
    timezone: `Central Pacific Standard Time`,
    utc: `UTC+11:00`,
    mobileCode: `+672`,
    flag: `🇳🇫`,
  },
  KP: {
    name: `North Korea`,
    code: `KP`,
    timezone: `Korea Standard Time`,
    utc: `UTC+09:00`,
    mobileCode: `+850`,
    flag: `🇰🇵`,
  },
  MP: {
    name: `Northern Mariana Islands`,
    code: `MP`,
    timezone: `West Pacific Standard Time`,
    utc: `UTC+10:00`,
    mobileCode: `+1-670`,
    flag: `🇲🇵`,
  },
  NO: {
    name: `Norway`,
    code: `NO`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+47`,
    flag: `🇳🇴`,
  },
  OM: {
    name: `Oman`,
    code: `OM`,
    timezone: `Arabian Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+968`,
    flag: `🇴🇲`,
  },
  PK: {
    name: `Pakistan`,
    code: `PK`,
    timezone: `Pakistan Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+92`,
    flag: `🇵🇰`,
  },
  PW: {
    name: `Palau`,
    code: `PW`,
    timezone: `Tokyo Standard Time`,
    utc: `UTC+09:00`,
    mobileCode: `+680`,
    flag: `🇵🇼`,
  },
  PS: {
    name: `Palestinian Authority`,
    code: `PS`,
    timezone: `Egypt Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+970`,
    flag: `🇵🇸`,
  },
  PA: {
    name: `Panama`,
    code: `PA`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+507`,
    flag: `🇵🇦`,
  },
  PG: {
    name: `Papua New Guinea`,
    code: `PG`,
    timezone: `West Pacific Standard Time`,
    utc: `UTC+10:00`,
    mobileCode: `+675`,
    flag: `🇵🇬`,
  },
  PY: {
    name: `Paraguay`,
    code: `PY`,
    timezone: `Paraguay Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+595`,
    flag: `🇵🇾`,
  },
  PE: {
    name: `Peru`,
    code: `PE`,
    timezone: `SA Pacific Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+51`,
    flag: `🇵🇪`,
  },
  PH: {
    name: `Philippines`,
    code: `PH`,
    timezone: `Singapore Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+63`,
    flag: `🇵🇭`,
  },
  PN: {
    name: `Pitcairn Islands`,
    code: `PN`,
    timezone: `Pacific Standard Time`,
    utc: `UTC-08:00`,
    mobileCode: `+870`,
    flag: `🇵🇳`,
  },
  PL: {
    name: `Poland`,
    code: `PL`,
    timezone: `Central European Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+48`,
    flag: `🇵🇱`,
  },
  PT: {
    name: `Portugal`,
    code: `PT`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+351`,
    flag: `🇵🇹`,
  },
  PR: {
    name: `Puerto Rico`,
    code: `PR`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-787 and 1-939`,
    flag: `🇵🇷`,
  },
  QA: {
    name: `Qatar`,
    code: `QA`,
    timezone: `Arab Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+974`,
    flag: `🇶🇦`,
  },
  RE: {
    name: `Reunion`,
    code: `RE`,
    timezone: `Mauritius Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+262`,
    flag: `🇷🇪`,
  },
  RO: {
    name: `Romania`,
    code: `RO`,
    timezone: `GTB Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+40`,
    flag: `🇷🇴`,
  },
  RU: {
    name: `Russia`,
    code: `RU`,
    timezone: `Russian Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+7`,
    flag: `🇷🇺`,
  },
  RW: {
    name: `Rwanda`,
    code: `RW`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+250`,
    flag: `🇷🇼`,
  },
  BL: {
    name: `Saint Barthélemy`,
    code: `BL`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+590`,
    flag: `🇧🇱`,
  },
  SH: {
    name: `Saint Helena, Ascension and Tristan da Cunha`,
    code: `SH`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+290`,
    flag: `🇸🇭`,
  },
  KN: {
    name: `Saint Kitts and Nevis`,
    code: `KN`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-869`,
    flag: `🇰🇳`,
  },
  LC: {
    name: `Saint Lucia`,
    code: `LC`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-758`,
    flag: `🇱🇨`,
  },
  MF: {
    name: `Saint Martin`,
    code: `MF`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+590`,
    flag: `🇲🇫`,
  },
  PM: {
    name: `Saint Pierre and Miquelon`,
    code: `PM`,
    timezone: `Greenland Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+508`,
    flag: `🇵🇲`,
  },
  VC: {
    name: `Saint Vincent and the Grenadines`,
    code: `VC`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-784`,
    flag: `🇻🇨`,
  },
  WS: {
    name: `Samoa`,
    code: `WS`,
    timezone: `Samoa Standard Time`,
    utc: `UTC+13:00`,
    mobileCode: `+685`,
    flag: `🇼🇸`,
  },
  SM: {
    name: `San Marino`,
    code: `SM`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+378`,
    flag: `🇸🇲`,
  },
  ST: {
    name: `São Tomé and Príncipe`,
    code: `ST`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+239`,
    flag: `🇸🇹`,
  },
  SA: {
    name: `Saudi Arabia`,
    code: `SA`,
    timezone: `Arab Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+966`,
    flag: `🇸🇦`,
  },
  SN: {
    name: `Senegal`,
    code: `SN`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+221`,
    flag: `🇸🇳`,
  },
  RS: {
    name: `Serbia`,
    code: `RS`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+381`,
    flag: `🇷🇸`,
  },
  SC: {
    name: `Seychelles`,
    code: `SC`,
    timezone: `Mauritius Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+248`,
    flag: `🇸🇨`,
  },
  SL: {
    name: `Sierra Leone`,
    code: `SL`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+232`,
    flag: `🇸🇱`,
  },
  SG: {
    name: `Singapore`,
    code: `SG`,
    timezone: `Singapore Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+65`,
    flag: `🇸🇬`,
  },
  SX: {
    name: `Sint Maarten`,
    code: `SX`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+721`,
    flag: `🇸🇽`,
  },
  SK: {
    name: `Slovakia`,
    code: `SK`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+421`,
    flag: `🇸🇰`,
  },
  SI: {
    name: `Slovenia`,
    code: `SI`,
    timezone: `Central Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+386`,
    flag: `🇸🇮`,
  },
  SB: {
    name: `Solomon Islands`,
    code: `SB`,
    timezone: `Central Pacific Standard Time`,
    utc: `UTC+11:00`,
    mobileCode: `+677`,
    flag: `🇸🇧`,
  },
  SO: {
    name: `Somalia`,
    code: `SO`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+252`,
    flag: `🇸🇴`,
  },
  ZA: {
    name: `South Africa`,
    code: `ZA`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+27`,
    flag: `🇿🇦`,
  },
  GS: {
    name: `South Georgia and the South Sandwich Islands`,
    code: `GS`,
    timezone: `UTC-02`,
    utc: `UTC-02:00`,
    mobileCode: `+`,
    flag: `🇬🇸`,
  },
  SS: {
    name: `South Sudan`,
    code: `SS`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+211`,
    flag: `🇸🇸`,
  },
  ES: {
    name: `Spain`,
    code: `ES`,
    timezone: `Romance Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+34`,
    flag: `🇪🇸`,
  },
  LK: {
    name: `Sri Lanka`,
    code: `LK`,
    timezone: `Sri Lanka Standard Time`,
    utc: `UTC+05:30`,
    mobileCode: `+94`,
    flag: `🇱🇰`,
  },
  SD: {
    name: `Sudan`,
    code: `SD`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+249`,
    flag: `🇸🇩`,
  },
  SR: {
    name: `Suriname`,
    code: `SR`,
    timezone: `SA Eastern Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+597`,
    flag: `🇸🇷`,
  },
  SZ: {
    name: `Swaziland`,
    code: `SZ`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+268`,
    flag: `🇸🇿`,
  },
  SE: {
    name: `Sweden`,
    code: `SE`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+46`,
    flag: `🇸🇪`,
  },
  CH: {
    name: `Switzerland`,
    code: `CH`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+41`,
    flag: `🇨🇭`,
  },
  SY: {
    name: `Syria`,
    code: `SY`,
    timezone: `Syria Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+963`,
    flag: `🇸🇾`,
  },
  TW: {
    name: `Taiwan`,
    code: `TW`,
    timezone: `Taipei Standard Time`,
    utc: `UTC+08:00`,
    mobileCode: `+886`,
    flag: `🇹🇼`,
  },
  TJ: {
    name: `Tajikistan`,
    code: `TJ`,
    timezone: `West Asia Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+992`,
    flag: `🇹🇯`,
  },
  TZ: {
    name: `Tanzania`,
    code: `TZ`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+255`,
    flag: `🇹🇿`,
  },
  TH: {
    name: `Thailand`,
    code: `TH`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+66`,
    flag: `🇹🇭`,
  },
  TG: {
    name: `Togo`,
    code: `TG`,
    timezone: `Greenwich Standard Time`,
    utc: `UTC`,
    mobileCode: `+228`,
    flag: `🇹🇬`,
  },
  TK: {
    name: `Tokelau`,
    code: `TK`,
    timezone: `Tonga Standard Time`,
    utc: `UTC+13:00`,
    mobileCode: `+690`,
    flag: `🇹🇰`,
  },
  TO: {
    name: `Tonga`,
    code: `TO`,
    timezone: `Tonga Standard Time`,
    utc: `UTC+13:00`,
    mobileCode: `+676`,
    flag: `🇹🇴`,
  },
  TT: {
    name: `Trinidad and Tobago`,
    code: `TT`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-868`,
    flag: `🇹🇹`,
  },
  TN: {
    name: `Tunisia`,
    code: `TN`,
    timezone: `W. Central Africa Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+216`,
    flag: `🇹🇳`,
  },
  TR: {
    name: `Turkey`,
    code: `TR`,
    timezone: `Turkey Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+90`,
    flag: `🇹🇷`,
  },
  TM: {
    name: `Turkmenistan`,
    code: `TM`,
    timezone: `West Asia Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+993`,
    flag: `🇹🇲`,
  },
  TC: {
    name: `Turks and Caicos Islands`,
    code: `TC`,
    timezone: `Eastern Standard Time`,
    utc: `UTC-05:00`,
    mobileCode: `+1-649`,
    flag: `🇹🇨`,
  },
  TV: {
    name: `Tuvalu`,
    code: `TV`,
    timezone: `UTC+12`,
    utc: `UTC+12:00`,
    mobileCode: `+688`,
    flag: `🇹🇻`,
  },
  UM: {
    name: `U.S. Minor Outlying Islands`,
    code: `UM`,
    timezone: `UTC-11`,
    utc: `UTC-11:00`,
    mobileCode: `+1`,
    flag: `🇺🇲`,
  },
  UG: {
    name: `Uganda`,
    code: `UG`,
    timezone: `E. Africa Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+256`,
    flag: `🇺🇬`,
  },
  UA: {
    name: `Ukraine`,
    code: `UA`,
    timezone: `FLE Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+380`,
    flag: `🇺🇦`,
  },
  AE: {
    name: `United Arab Emirates`,
    code: `AE`,
    timezone: `Arabian Standard Time`,
    utc: `UTC+04:00`,
    mobileCode: `+971`,
    flag: `🇦🇪`,
  },
  GB: {
    name: `United Kingdom`,
    code: `GB`,
    timezone: `GMT Standard Time`,
    utc: `UTC`,
    mobileCode: `+44`,
    flag: `🇬🇧`,
  },
  US: {
    name: `United States`,
    code: `US`,
    timezone: `Pacific Standard Time`,
    utc: `UTC-08:00`,
    mobileCode: `+1`,
    flag: `🇺🇸`,
  },
  UY: {
    name: `Uruguay`,
    code: `UY`,
    timezone: `Montevideo Standard Time`,
    utc: `UTC-03:00`,
    mobileCode: `+598`,
    flag: `🇺🇾`,
  },
  UZ: {
    name: `Uzbekistan`,
    code: `UZ`,
    timezone: `West Asia Standard Time`,
    utc: `UTC+05:00`,
    mobileCode: `+998`,
    flag: `🇺🇿`,
  },
  VU: {
    name: `Vanuatu`,
    code: `VU`,
    timezone: `Central Pacific Standard Time`,
    utc: `UTC+11:00`,
    mobileCode: `+678`,
    flag: `🇻🇺`,
  },
  VA: {
    name: `Vatican City`,
    code: `VA`,
    timezone: `W. Europe Standard Time`,
    utc: `UTC+01:00`,
    mobileCode: `+379`,
    flag: `🇻🇦`,
  },
  VN: {
    name: `Vietnam`,
    code: `VN`,
    timezone: `SE Asia Standard Time`,
    utc: `UTC+07:00`,
    mobileCode: `+84`,
    flag: `🇻🇳`,
  },
  VI: {
    name: `Virgin Islands, U.S.`,
    code: `VI`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-340`,
    flag: `🇻🇮`,
  },
  VG: {
    name: `Virgin Islands, British`,
    code: `VG`,
    timezone: `SA Western Standard Time`,
    utc: `UTC-04:00`,
    mobileCode: `+1-284`,
    flag: `🇻🇬`,
  },
  WF: {
    name: `Wallis and Futuna`,
    code: `WF`,
    timezone: `UTC+12`,
    utc: `UTC+12:00`,
    mobileCode: `+681`,
    flag: `🇼🇫`,
  },
  YE: {
    name: `Yemen`,
    code: `YE`,
    timezone: `Arab Standard Time`,
    utc: `UTC+03:00`,
    mobileCode: `+967`,
    flag: `🇾🇪`,
  },
  ZM: {
    name: `Zambia`,
    code: `ZM`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+260`,
    flag: `🇿🇲`,
  },
  ZW: {
    name: `Zimbabwe`,
    code: `ZW`,
    timezone: `South Africa Standard Time`,
    utc: `UTC+02:00`,
    mobileCode: `+263`,
    flag: `🇿🇼`,
  },
}
