name: CI Web

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - ".github/workflows/ci-ui.yaml"
      - "modules/meteroid/proto/**"
      - "modules/web/**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      TURBO_TELEMETRY_DISABLED: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "modules/web/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --prefix modules/web
      - name: Run lint
        run: pnpm --prefix modules/web lint
